# .yaml config file
#
# The PID gains and controller settings must be saved in a yaml file that gets loaded
# to the param server via the roslaunch file (monoped_control.launch).

hyq:
  # Publish all joint states -----------------------------------
  # Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Effort Controllers ---------------------------------------

  #-------------------------lf-----------------------------------
  lf_haa_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: lf_haa_joint
    pid: {p: 10.0, i: 0.0, d: 0.5}
    #pid: {p: 50.0, i: 0.1, d: 0.0}
  lf_hfe_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: lf_hfe_joint
    pid: {p: 10.0, i: 0.0, d: 0.5}
    #pid: {p: 50.0, i: 0.1, d: 0.0}
  lf_kfe_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: lf_kfe_joint
    pid: {p: 10.0, i: 0.0, d: 0.5}

    #----------------------rf---------------------------

  rf_haa_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: rf_haa_joint
    pid: {p: 10.0, i: 0.0, d: 0.5}
    #pid: {p: 50.0, i: 0.1, d: 0.0}
  rf_hfe_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: rf_hfe_joint
    pid: {p: 10.0, i: 0.0, d: 0.5}
    #pid: {p: 50.0, i: 0.1, d: 0.0}
  rf_kfe_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: rf_kfe_joint
    pid: {p: 10.0, i: 0.0, d: 0.5}

    #------------------------lh-----------------------------------

  lh_haa_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: lh_haa_joint
    pid: {p: 10.0, i: 0.0, d: 0.5}
    #pid: {p: 50.0, i: 0.1, d: 0.0}
  lh_hfe_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: lh_hfe_joint
    pid: {p: 10.0, i: 0.0, d: 0.5}
    #pid: {p: 50.0, i: 0.1, d: 0.0}
  lh_kfe_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: lh_kfe_joint
    pid: {p: 10.0, i: 0.0, d: 0.5}

    #-----------------rh------------------------------------------


  rh_haa_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: rh_haa_joint
    pid: {p: 10.0, i: 0.0, d: 0.5}
    #pid: {p: 50.0, i: 0.1, d: 0.0}
  rh_hfe_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: rh_hfe_joint
    pid: {p: 10.0, i: 0.0, d: 0.5}
    #pid: {p: 50.0, i: 0.1, d: 0.0}
  rh_kfe_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: rh_kfe_joint
    pid: {p: 10.0, i: 0.0, d: 0.5}